#!/usr/bin/env python3
"""
Issue Resolver Agent

Reads a GitHub issue, uses OpenHands agent to implement a fix/feature,
runs tests, and creates a pull request.

Environment Variables:
    LLM_API_KEY: API key for the LLM (required)
    LLM_MODEL: Language model to use (default: openai/glm-5.2)
    LLM_BASE_URL: Base URL for LLM API (default: https://api.modelarts-maas.com/v2)
    GITHUB_TOKEN: GitHub token for API access (required)
    ISSUE_NUMBER: Issue number to resolve (required)
    ISSUE_TYPE: 'issue' or 'pr' (default: issue)
    MAX_ITERATIONS: Maximum agent iterations (default: 50)
    REPO_NAME: Repository name in format owner/repo (required)
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path


def get_required_env(name: str) -> str:
    value = os.getenv(name)
    if not value:
        raise ValueError(f"{name} environment variable is required")
    return value


def fetch_issue(repo_name: str, issue_number: int, github_token: str) -> dict:
    """Fetch issue details from GitHub API."""
    import urllib.request

    url = f"https://api.github.com/repos/{repo_name}/issues/{issue_number}"
    req = urllib.request.Request(url, headers={
        "Authorization": f"token {github_token}",
        "Accept": "application/vnd.github+json",
    })
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.load(resp)


def fetch_issue_comments(repo_name: str, issue_number: int, github_token: str) -> list:
    """Fetch comments on the issue for additional context."""
    import urllib.request

    url = f"https://api.github.com/repos/{repo_name}/issues/{issue_number}/comments"
    req = urllib.request.Request(url, headers={
        "Authorization": f"token {github_token}",
        "Accept": "application/vnd.github+json",
    })
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.load(resp)


def comment_on_issue(repo_name: str, issue_number: int, body: str, github_token: str):
    """Post a comment on the issue."""
    import urllib.request

    url = f"https://api.github.com/repos/{repo_name}/issues/{issue_number}/comments"
    payload = json.dumps({"body": body}).encode()
    req = urllib.request.Request(
        url, data=payload,
        headers={
            "Authorization": f"token {github_token}",
            "Accept": "application/vnd.github+json",
        },
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.load(resp)


def create_branch(issue_number: int, issue_type: str) -> str:
    """Create a new branch for the fix."""
    branch_name = f"openhands/fix-{issue_type}-{issue_number}"
    subprocess.run(["git", "checkout", "-b", branch_name], check=True)
    return branch_name


def create_pull_request(
    repo_name: str,
    issue_number: int,
    issue_title: str,
    branch_name: str,
    base_branch: str,
    summary: str,
    github_token: str,
) -> dict:
    """Create a pull request on GitHub."""
    import urllib.request

    url = f"https://api.github.com/repos/{repo_name}/pulls"
    payload = json.dumps({
        "title": f"Fix #{issue_number}: {issue_title}",
        "body": f"## Automated Fix\n\n{summary}\n\nCloses #{issue_number}\n\n---\nGenerated by OpenHands Issue Resolver using GLM-5.2",
        "head": branch_name,
        "base": base_branch,
    }).encode()

    req = urllib.request.Request(
        url, data=payload,
        headers={
            "Authorization": f"token {github_token}",
            "Accept": "application/vnd.github+json",
        },
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.load(resp)


def run_tests() -> bool:
    """Try to run tests. Returns True if tests pass, False otherwise."""
    cwd = os.getcwd()

    # Try different test commands based on project type
    test_commands = []

    if Path("Cargo.toml").exists():
        test_commands.append(["cargo", "test", "--", "--nocapture"])
    if Path("package.json").exists():
        test_commands.append(["npm", "test", "--", "--passWithNoTests"])
    if Path("pytest.ini").exists() or Path("setup.py").exists():
        test_commands.append(["pytest", "-x"])

    if not test_commands:
        print("No test framework detected, skipping tests")
        return True

    for cmd in test_commands:
        print(f"Running tests: {' '.join(cmd)}")
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
        if result.returncode != 0:
            print(f"Tests failed: {result.stderr[:500]}")
            return False
        print(f"Tests passed: {result.stdout[:200]}")

    return True


def has_changes() -> bool:
    """Check if there are uncommitted changes."""
    result = subprocess.run(
        ["git", "status", "--porcelain"],
        capture_output=True, text=True,
    )
    return bool(result.stdout.strip())


def commit_changes(issue_number: int, issue_title: str):
    """Commit all changes."""
    subprocess.run(["git", "add", "-A"], check=True)
    subprocess.run(
        ["git", "commit", "-m", f"Fix #{issue_number}: {issue_title}\n\nGenerated by OpenHands Issue Resolver"],
        check=True,
    )


def push_branch(branch_name: str):
    """Push branch to remote."""
    subprocess.run(["git", "push", "-u", "origin", branch_name], check=True)


def main():
    print("=" * 60)
    print("OpenHands Issue Resolver")
    print("=" * 60)

    # Get configuration
    api_key = get_required_env("LLM_API_KEY")
    model = os.getenv("LLM_MODEL", "openai/glm-5.2")
    base_url = os.getenv("LLM_BASE_URL", "https://api.modelarts-maas.com/v2")
    github_token = get_required_env("GITHUB_TOKEN")
    issue_number = int(get_required_env("ISSUE_NUMBER"))
    issue_type = os.getenv("ISSUE_TYPE", "issue")
    max_iterations = int(os.getenv("MAX_ITERATIONS", "50"))
    repo_name = get_required_env("REPO_NAME")

    print(f"Repository: {repo_name}")
    print(f"Issue: #{issue_number} ({issue_type})")
    print(f"Model: {model}")
    print(f"Base URL: {base_url}")

    # Fetch issue
    issue = fetch_issue(repo_name, issue_number, github_token)
    issue_title = issue["title"]
    issue_body = issue.get("body", "") or "(no description)"

    print(f"\nIssue Title: {issue_title}")
    print(f"Issue Body: {issue_body[:200]}...")

    # Fetch comments for context
    comments = fetch_issue_comments(repo_name, issue_number, github_token)
    if comments:
        print(f"\nIssue has {len(comments)} comments")

    # Comment on issue - started
    comment_on_issue(
        repo_name, issue_number,
        f"🤖 OpenHands started working on this issue using GLM-5.2.\n\nMonitor progress in the [workflow run](https://github.com/{repo_name}/actions).",
        github_token,
    )

    # Build the task prompt
    comments_text = ""
    if comments:
        comments_text = "\n\n## Additional Context from Comments:\n"
        for c in comments:
            comments_text += f"\n**{c['user']['login']}**:\n{c['body']}\n"

    task_prompt = f"""You are a software engineer working on the repository: {repo_name}

## Issue to Resolve
**Title**: {issue_title}
**Description**:
{issue_body}
{comments_text}

## Your Task
1. Explore the codebase to understand the project structure
2. Identify the root cause or what needs to be implemented
3. Make the necessary code changes to resolve this issue
4. Run the tests to verify your changes work
5. If tests fail, analyze the errors and fix your changes
6. Ensure code quality and follow existing code style

## Important
- Make minimal, focused changes
- Follow existing code conventions
- Don't break existing functionality
- If you're unsure about something, make a reasonable decision and proceed

Start by exploring the project structure, then implement the fix.
"""

    # Create agent and run
    from openhands.sdk import LLM, Agent, Conversation, get_logger
    from openhands.tools.preset.default import get_default_condenser, get_default_tools

    logger = get_logger(__name__)
    logger.info("Creating OpenHands agent...")

    llm_config = {
        "model": model,
        "api_key": api_key,
        "usage_id": "issue_resolver",
        "drop_params": True,
    }
    if base_url:
        llm_config["base_url"] = base_url

    llm = LLM(**llm_config)

    agent = Agent(
        llm=llm,
        tools=get_default_tools(enable_browser=False),
        system_prompt_kwargs={"cli_mode": True},
        condenser=get_default_condenser(
            llm=llm.model_copy(update={"usage_id": "condenser"})
        ),
    )

    cwd = os.getcwd()
    secrets = {
        "LLM_API_KEY": api_key,
        "GITHUB_TOKEN": github_token,
    }

    logger.info("Starting agent conversation...")
    conversation = Conversation(
        agent=agent,
        workspace=cwd,
        secrets=secrets,
    )

    try:
        conversation.send_message(task_prompt)
        conversation.run()
        logger.info("Agent completed successfully")
    except Exception as e:
        logger.error(f"Agent failed: {type(e).__name__}: {e}")
        comment_on_issue(
            repo_name, issue_number,
            f"❌ OpenHands encountered an error: {e}\n\nPlease check the [workflow logs](https://github.com/{repo_name}/actions).",
            github_token,
        )
        sys.exit(1)

    # Check if there are changes
    if not has_changes():
        print("No changes were made by the agent")
        comment_on_issue(
            repo_name, issue_number,
            "⚠️ OpenHands analyzed the issue but no code changes were made. The issue might need manual intervention.",
            github_token,
        )
        sys.exit(0)

    # Run tests
    print("\nRunning tests...")
    tests_pass = run_tests()

    if not tests_pass:
        print("Tests failed, but still creating PR for review")
        comment_on_issue(
            repo_name, issue_number,
            "⚠️ OpenHands made changes but tests failed. A PR has been created for manual review.",
            github_token,
        )

    # Create branch and commit
    base_branch = subprocess.run(
        ["git", "rev-parse", "--abbrev-ref", "HEAD"],
        capture_output=True, text=True,
    ).stdout.strip()

    branch_name = create_branch(issue_number, issue_type)
    commit_changes(issue_number, issue_title)
    push_branch(branch_name)

    # Create PR
    summary = f"Automated fix for issue #{issue_number}"
    pr = create_pull_request(
        repo_name, issue_number, issue_title,
        branch_name, base_branch, summary, github_token,
    )

    pr_url = pr.get("html_url", "unknown")
    pr_number = pr.get("number", "?")
    print(f"\n✅ Pull Request created: {pr_url}")

    # Comment on issue with PR link
    status_emoji = "✅" if tests_pass else "⚠️"
    test_status = "Tests passed" if tests_pass else "Tests failed - needs review"
    comment_on_issue(
        repo_name, issue_number,
        f"{status_emoji} OpenHands created PR #{pr_number}: {pr_url}\n\n**Status**: {test_status}\n**Model**: GLM-5.2 via MAAS",
        github_token,
    )

    print("\n" + "=" * 60)
    print(f"Issue #{issue_number} resolved!")
    print(f"PR: {pr_url}")
    print(f"Tests: {'passed' if tests_pass else 'failed'}")
    print("=" * 60)


if __name__ == "__main__":
    main()
